--JUL 13

CREATE TABLE room (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  password VARCHAR(255),
  hash VARCHAR(255),
  player_num INT(5)
)

CREATE TABLE player (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nick_name VARCHAR(255),
  socket_id VARCHAR(255)
)

-- Jul 15

ALTER TABLE room ADD COLUMN number INT(10) NOT NULL;
ALTER TABLE player ADD COLUMN ready INT(1) DEFAULT 0;
ALTER TABLE player ADD COLUMN room_id INT(10) NOT NULL;

-- Jul 19

ALTER TABLE room ADD COLUMN status VARCHAR(255) DEFAULT 'waiting';